### PR TITLE
Migrate to null safety

### LINKED ISSUE #67: Migrate to null safety
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description
I propose this pull request to [migrate this plugin to null safety](https://dart.dev/null-safety/migration-guide) as it is the way to go now that Flutter 2 has been released.

Here are the changes I introduced:
* Update SDK dependency version to 2.12.0+
* Run `dart migrate` on existing code to remove unsafe nulls (for the package & example)
* Changed `FlatButton` to `TextButton` and `RaisedButton` to `ElevationButton`
* Add a new version (`0.14.0`) to the changelog

Please check everything twice!

## Testing
- [x] All existing Tests are passing
- [x] Tested it manually on a Android emulator 

Demo:

https://user-images.githubusercontent.com/24459435/110187638-50370f80-7e19-11eb-9b44-e916ab27236c.mov

### Related tickets
Closes #67

### CODE REVIEW

**Comment by blaueeiner** [comment]
Hi. You should maybe support compatibility with provider: 5.0.0-nullsafety.5 because flutter_bloc currently does not support 5.0.0 yet and it causes versioning issues.

**Comment by nilsreichardt** [comment]
Hi @blaueeiner! As you can see in https://github.com/felangel/bloc/issues/2202 `flutter_bloc` will be updated today / tomorrow and after this there should be no versioning conflicts.

**Comment by luckyhandler** [comment]
nice work!

**Comment by sangTroo** [comment]
Hi,
Thanks for the great work
 When This new version will be available on pub.dev?

**Comment by JaffaKetchup** [comment]
Hi, any news on this?

**Comment by nilsreichardt** [comment]
As long as the PR has not been merged, you can use this in your `pubspec.yaml`:
```yaml
feature_discovery:
  git:
    url: https://github.com/nilsreichardt/feature_discovery
    ref: migrate-null-safety
```

**Comment by JaffaKetchup** [comment]
Hi @nilsreichardt.
Thanks for the tip, however I'm already using it like that. I just don't like having packages from git in my code if I can help it. :)

**Comment by nilsreichardt** [comment]
@JaffaKetchup Yes, I understand this. If I delete the `migrate-null-safety` branch / my repo / rename my GitHub username, etc., your code would break 😬

**Comment by nosmirck** [comment]
any news on when will this be merged?

**Comment by JaffaKetchup** [comment]
Hi,
Any news on this?
Thanks.

**Comment by jagomf** [comment]
@ayalma, the owner of this repo, has not given any proof of life ever since November 2020. His website, as reported by his bio, is also offline.

It is not a good idea to rely on a package that cannot be maintained. The best option would probably be for anyone that can maintain this to publish the package.

@nilsreichardt would you be willing to publishing and maintaining this package maybe?

**Comment by nilsreichardt** [comment]
@jagomf I'm sorry, but I don't have to maintain this package 😖 Maybe @FlutterCommunity can do this?

**Comment by ayalma** [comment]
I'm in nowruz holiday , and  cuz of that I can't do anything for that

**Comment by nosmirck** [comment]
> I'm in nowruz holiday , and  cuz of that I can't do anything for that
> 
@ayalma so maybe by April 12 we'll have this merged?

**Comment by ayalma** [comment]
I'll give it a try

**Comment by ayalma** [comment]
@nilsreichardt @blaueeiner @JaffaKetchup @luckyhandler @sangTroo   published to pubspec.

**Comment by JaffaKetchup** [comment]
Hi, any news on this?

**Pull request merged**
