### PR TITLE
fix flutter 3 compatibility warnings

### PR DESCRIPTION
**Pull request by P-B1101**
just run `dart fix --apply`

### CODE REVIEW

**Comment by awazgyawali** [comment]
@ayalma We would really appreciate if you could merge and release this.

Thanks in advance.

**Review by jagomf — APPROVED** [review]

**Comment by vytautas-pranskunas-** [comment]
Hello, how to get this fix to the project?

**Comment by jagomf** [comment]
@danielgomezrico I definitely wish so, but it's on @ayalma to do that.

**Comment by danielgomezrico** [comment]
@ayalma 👀 ping

**Comment by marciocesarcorrea** [comment]
@ayalma 👀 ping

**Comment by maheshj01** [comment]
for latest fix use this https://github.com/ayalma/feature_discovery/pull/99#issuecomment-2111207063

**Comment by ayalma** [comment]
all done with new release

**Pull request closed without merging**
