### PR TITLE
Fix textTheme deprecation and null safety issue

### PR DESCRIPTION
**Pull request by maheshj01**
deprecation fix as per https://docs.flutter.dev/release/breaking-changes/3-19-deprecations

### CODE REVIEW

**Comment by maheshmnj** [comment]
Anyone awaiting for this fix to be merged you can add this to your pubspec.yaml

```yaml
  feature_discovery:
    git:
      url: https://github.com/maheshmnj/feature_discovery.git
      ref: master
```

**Comment by deakjahn** [comment]
Thanks but considering that there are almost a dozen outstanding PRs... Sad to see this abandoned.

**Comment by TheFe91** [comment]
@maheshmnj you should consider to publish your version to pub.dev with a new name maybe

**Comment by maheshmnj** [comment]
@TheFe91 I don't think it would be right to publish someone else's work. Also, I can't promise any further updates to the package. But I can ensure this keeps running on future versions of flutter https://github.com/maheshmnj/feature_discovery.git

**Comment by richdreamalytics** [comment]
@ maheshj01 the packages has an MIT license, so it's fine republish, but I take your point about not being able to guarantee future support.

**Comment by ayalma** [comment]
all this issue fixed

**Pull request closed without merging**
