### PR TITLE
Introduce a PersistenceProvider interface to govern storage.

### PR DESCRIPTION
**Pull request by noordawod**

### CODE REVIEW

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by noordawod** [comment]
Bump @ayalma

**Comment by ayalma** [comment]
Merged and published thanks to you
@noordawod

**Pull request merged**
